### ISSUE TITLE
set_preset_mode "none" (Auto) not working

### ISSUE THREAD

**Issue by Barry-Ricoh** [piitaya/lovelace-climate-mode-entity-row#18]
Hello,
I´ve been using this card for my Climate Controll.
I only use "Preset_Modes", no "HVAC_Modes", because it is only for heating.
I use this simple code:

`type: entities
entities:
  - entity: climate.schlafzimmer
    type: custom:climate-mode-entity-row
    icon: mdi:home
    modes:
      - preset_mode: auto
      - preset_mode: comfort
      - preset_mode: away
        icon: mdi:leaf
        color: '#76D275'
      - preset_mode: sleep
        color: '#FFC107'
      - preset_mode: eco
        icon: mdi:snowflake
        color: '#34c6eb'
state_color: true`

Every time i click on the "Auto" Icon to set the mode to Auto (Scheduler) there comes a error message:

"Fehler beim Aufrufen des Dienstes climate/set_preset_mode. None is not a valid HVACOperationMode"

On other cards (e.g. simple thermostat) this is working perfect.

**Comment by Barry-Ricoh** [comment]
Here is the log:

2022-11-30 21:49:37.346 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547810340400] None is not a valid HVACOperationMode
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/knx/climate.py", line 275, in async_set_preset_mode
knx_operation_mode = HVACOperationMode(PRESET_MODES_INV.get(preset_mode))
File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
return cls.__new__(cls, value)
File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
raise ve_exc
ValueError: None is not a valid HVACOperationMode
